// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvdnhognapqyafgfdcod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2ZG5ob2duYXBxeWFmZ2ZkY29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDQ1NTcsImV4cCI6MjA3NDU4MDU1N30.5hINozqkjojMAoqiUFjYmk1ieZAbVSLAIrKKzGJFFlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});